### ISSUE TITLE
Question about that Angular CLI tar file...

### ISSUE THREAD

**Issue by joerossetter** [jasonaden/angular-cli-lib-example#5]
why do you use an `.angular_cli.tgz` in the project root instead of just installing a version from npm using the `package.json`?

**Comment by jpconsi** [comment]
This sample is using the nrwl nx schematic which produces that file.  The .angular_cli.tgz is being used to fix the version of angular-cli,  what nrwl calls sandboxing. This is desired for enterprise applications so that many projects being developed at the same time are not impacted by angular-cli version changes of other projects (apps or libs).

**Comment by joerossetter** [comment]
thanks for the response! funny enough, looks like that's changing slightly in nrwl going forward.

https://github.com/nrwl/nx/commit/acdeb1b71c14e3bc7e5bd2bc925640ad7d0aa24d
